# Generated by Django 2.2 on 2019-04-23 14:08

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.datetime_safe import date


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Membro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cpf', models.BigIntegerField()),
                ('rg', models.BigIntegerField()),
                ('dataDeNascimento', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Familia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('dataDeCadastro', models.DateField(default=date(2019, 4, 23))),
                ('administrador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pessoal.Membro')),
            ],
        ),
    ]
