# Generated by Django 2.2 on 2019-04-23 14:13

from django.db import migrations, models
import django.utils.datetime_safe


class Migration(migrations.Migration):

    dependencies = [
        ('pessoal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familia',
            name='dataDeCadastro',
            field=models.DateField(default=django.utils.datetime_safe.date.today),
        ),
    ]
