# Generated by Django 2.2 on 2019-04-25 00:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ambiental', '0005_remove_propriedade_administrador'),
        ('pessoal', '0003_auto_20190423_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='familia',
            name='adm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ambiental.Propriedade'),
        ),
    ]
