# Generated by Django 2.2 on 2019-04-27 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoal', '0005_remove_familia_adm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familia',
            name='nome',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='membro',
            name='cpf',
            field=models.BigIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='membro',
            name='nome',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='membro',
            name='rg',
            field=models.BigIntegerField(unique=True),
        ),
    ]
