# Generated by Django 2.2 on 2019-04-23 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pessoal', '0003_auto_20190423_1602'),
        ('ambiental', '0003_auto_20190423_1125'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propriedade',
            name='proprietario',
        ),
        migrations.AddField(
            model_name='propriedade',
            name='administrador',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='pessoal.Membro'),
            preserve_default=False,
        ),
    ]
