# Generated by Django 2.2 on 2019-04-25 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ambiental', '0004_auto_20190423_1602'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propriedade',
            name='administrador',
        ),
    ]
