# Generated by Django 2.2 on 2019-04-25 00:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pessoal', '0005_remove_familia_adm'),
        ('ambiental', '0005_remove_propriedade_administrador'),
    ]

    operations = [
        migrations.AddField(
            model_name='propriedade',
            name='responsalvel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pessoal.Membro'),
            preserve_default=False,
        ),
    ]
