# Generated by Django 2.2 on 2019-04-25 02:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ambiental', '0006_propriedade_responsalvel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propriedade',
            name='responsalvel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pessoal.Membro'),
        ),
    ]
