# Generated by Django 2.2 on 2019-04-25 02:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pessoal', '0005_remove_familia_adm'),
        ('ambiental', '0007_auto_20190424_2324'),
    ]

    operations = [
        migrations.AddField(
            model_name='propriedade',
            name='proprietario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='pessoal.Familia'),
            preserve_default=False,
        ),
    ]
