# Generated by Django 2.2 on 2019-04-27 02:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pessoal', '0005_remove_familia_adm'),
        ('ambiental', '0008_propriedade_proprietario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propriedade',
            name='responsalvel',
        ),
        migrations.AddField(
            model_name='propriedade',
            name='responsavel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pessoal.Membro'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='propriedade',
            name='proprietario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pessoal.Familia'),
        ),
    ]
