# Generated by Django 2.2 on 2019-04-27 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ambiental', '0009_auto_20190426_2327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propriedade',
            name='culturaPrimaria',
            field=models.ManyToManyField(blank=True, null=True, to='ambiental.Cultura'),
        ),
        migrations.AlterField(
            model_name='propriedade',
            name='rebanho1',
            field=models.ManyToManyField(blank=True, null=True, to='ambiental.Rebanho'),
        ),
    ]
