# Generated by Django 2.2 on 2019-04-27 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ambiental', '0010_auto_20190426_2343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propriedade',
            name='responsavel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pessoal.Membro', unique=True),
        ),
    ]
