# Generated by Django 2.2 on 2019-04-27 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ambiental', '0011_auto_20190427_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propriedade',
            name='responsavel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pessoal.Membro'),
        ),
    ]
