# Generated by Django 2.2 on 2019-05-14 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ambiental', '0013_auto_20190427_1501'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propriedade',
            name='culturaPrimaria',
        ),
        migrations.RemoveField(
            model_name='propriedade',
            name='rebanho1',
        ),
        migrations.AddField(
            model_name='cultura',
            name='propriedade',
            field=models.ManyToManyField(blank=True, null=True, to='ambiental.Propriedade'),
        ),
        migrations.AddField(
            model_name='rebanho',
            name='propriedade',
            field=models.ManyToManyField(blank=True, null=True, to='ambiental.Propriedade'),
        ),
    ]
