# Generated by Django 2.2 on 2019-05-14 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ambiental', '0014_auto_20190513_2142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cultura',
            name='propriedade',
            field=models.ManyToManyField(to='ambiental.Propriedade'),
        ),
        migrations.AlterField(
            model_name='rebanho',
            name='propriedade',
            field=models.ManyToManyField(to='ambiental.Propriedade'),
        ),
    ]
