# Generated by Django 2.2 on 2019-05-14 03:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ambiental', '0016_auto_20190514_0018'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cultura',
            name='propriedade',
        ),
        migrations.AddField(
            model_name='cultura',
            name='propriedade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ambiental.Propriedade'),
        ),
        migrations.RemoveField(
            model_name='rebanho',
            name='propriedade',
        ),
        migrations.AddField(
            model_name='rebanho',
            name='propriedade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ambiental.Propriedade'),
        ),
    ]
