# Generated by Django 2.2 on 2019-05-14 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ambiental', '0017_auto_20190514_0031'),
    ]

    operations = [
        migrations.AddField(
            model_name='rebanho',
            name='quantidade',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
