# Generated by Django 2.2.1 on 2019-05-11 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contaspagar', '0002_contaspagar_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='contaspagar',
            name='numero_parcela_total',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
