# Generated by Django 2.2.1 on 2019-05-11 03:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pessoal', '0007_familia_cooperativa'),
        ('cooperativa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContasReceber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('descricao', models.CharField(max_length=255)),
                ('data_documento', models.DateField()),
                ('data_recebimento', models.DateField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=8)),
                ('numero_parcela', models.IntegerField()),
                ('cooperativa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cooperativa.Cooperativa')),
                ('familia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pessoal.Familia')),
            ],
        ),
    ]
