# Generated by Django 2.2.1 on 2019-05-11 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contasreceber', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contasreceber',
            name='status',
            field=models.NullBooleanField(),
        ),
    ]
